format_version: v1.0
type: UniqueComponent
attributes: {id: spi1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SPI_CSR0_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '83'}
  - type: Integer
    attributes: {id: SPI_CSR1_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '83'}
  - type: Integer
    attributes: {id: SPI_CSR2_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '83'}
  - type: Integer
    attributes: {id: SPI_CSR3_SCBR_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '83'}
  - type: Integer
    attributes: {id: SPI_CSR_INDEX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '0'}
  - type: Boolean
    attributes: {id: SPI_EN_NPCS0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: 'true'}
  - type: Integer
    attributes: {id: SPI_MASTER_CLOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '83000000'}
  - type: KeyValueSet
    attributes: {id: SPI_MR_PCS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SPI_NUM_CSR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi1, value: '1'}
- type: ElementPosition
  attributes: {x: '440', y: '20', id: spi1}
