configName: sam_a5d2_xult_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\MCU_MPU\SAMA5\H3_MPU
processor: ATSAMA5D27
projectName: adc_user_sequence_sam_a5d2_xult_iar
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;net;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.2.16\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: USER_ALL
