package:
  format-version: "1.0.0"
  name: "csp_apps_sam_a5d2"
  version: "v3.5.0"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.3"
    - name: "dev_packs"
      type: "package"
      version: "v3.18.1"
    - name: "bsp"
      type: "package"
      version: "v3.17.1"