configName: sam_a5d2_xult_iar
folderName: ''
format_version: v1.0
frameworkPath: /home/dan/dev/h3
processor: ATSAMA5D27
projectName: clock_low_power_sam_a5d2_xult_iar
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.52\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: OVERWRITE
