format_version: v1.0
type: UniqueComponent
attributes: {id: twihs1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TWIHS_CLK_SRC_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs1, value: '83000000'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CHDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs1, value: '96'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CKDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs1, value: '0'}
  - type: Integer
    attributes: {id: TWIHS_CWGR_CLDIV}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: twihs1, value: '105'}
- type: ElementPosition
  attributes: {x: '400', y: '20', id: twihs1}
