format_version: v1.0
type: UniqueComponent
attributes: {id: rstc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: RSTC_MR_URSTEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rstc, value: '0'}
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '481', y: '20', id: rstc}
