configName: sam_a5d2_xult_iar
folderName: ''
format_version: v1.0
frameworkPath: C:\Users\C50921\HarmonyCode
processor: ATSAMA5D27
projectName: rstc_led_switcher_sam_a5d2_xult_iar
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\0.1.18\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: OVERWRITE
