configName: sam_a5d27_som1_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMA5D27CD1G
projectName: ''
settings:
  PackageFilter: bsp;core;csp;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.69\atdf\ATSAMA5D27CD1G.atdf
  MERGE_STRATEGY: OVERWRITE
