configName: sam_a5d27_som1_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMA5D27CD1G
projectName: ''
settings:
  PackageFilter: aws_cloud;bootloader_apps_uart;bsp;core;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;csp_apps_sam_rh71;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.3.35\atdf\ATSAMA5D27CD1G.atdf
  MERGE_STRATEGY: USER_ALL
