configName: sam_a5d2_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMA5D27
projectName: ''
settings:
  PackageFilter: bsp;core;csp
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.62\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: USER_ALL
