configName: sam_a5d27_som1_ek
folderName: sam_a5d27_som1_ek
format_version: v1.0
frameworkPath: ..\..\Harmony3
processor: ATSAMA5D27CD1G
projectName: uart_ring_buffer_interrupt_sam_a5d27_som1_ek
settings:
  PackageFilter: bsp;core;csp;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.6.69\atdf\ATSAMA5D27CD1G.atdf
