configName: sam_a5d2_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMA5D27
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;csp_apps_pic32cm_mc00;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_pic32mz_w1;csp_apps_sam_9x60;csp_apps_sam_a5d2;csp_apps_sam_c20_c21;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;csp_apps_sam_ha1;csp_apps_sam_l10_l11;csp_apps_sam_l21;csp_apps_sam_l22;csp_apps_sam_rh71;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.3.35\atdf\ATSAMA5D27.atdf
  MERGE_STRATEGY: USER_ALL
