configName: sam_a5d2_xult
folderName: sam_a5d2_xult
format_version: v1.0
frameworkPath: ..\..\..\..
processor: ATSAMA5D27
projectName: sam_a5d2_xult
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.52\atdf\ATSAMA5D27.atdf
