configName: sama5d29_curiosity
folderName: sama5d29_curiosity
format_version: v1.0
frameworkPath: C:\microchip\harmony\h3
processor: ATSAMA5D29
projectName: sama5d29_curiosity
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  MERGE_STRATEGY: USER_ALL
  DFPPath: SAMA5D2_DFP\1.10.213
