configName: sam_a5d2_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMA5D27
projectName: ''
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.1.10\atdf\ATSAMA5D27.atdf
